title: Shomrik Mondal
logo: /assets/img/headshot_circle.png
description: >
  Some description
  <br>
  <br>
  <a href="https://www.linkedin.com/in/shomrik/">View My Linkedin Profile</a>
show_downloads: true
theme: jekyll-theme-minimal
